### ISSUE TITLE
How can I get the full dataset for research purpose

### ISSUE THREAD

**Issue by GeneZC** [Meituan-Dianping/asap#1]
I have noticed that the dataset in this repo only contained a few samples. How can I get a full one for research purpose?

**Comment by bitwjg** [comment]
Hi GeneZc,

Thanks for your interest in our dataset.
The full dataset would be released next month.
Please stay tuned.
Thanks for your patience.

**Comment by sakuraukulele** [comment]
Hi May I ask where can i get the released data set? Many thanks

**Comment by blueseasky** [comment]
Hi, sakuraukulele,
The full datasets have been released.
