### ISSUE TITLE
请问你们的标注工具是什么呢？可以分享一下吗？

### ISSUE THREAD

**Issue by Heart-beatsss** [Meituan-Dianping/asap#2]
如题

**Comment by blueseasky** [comment]
我们的标注工具是公司内部开发的一套标注系统，暂未开源，所以暂时还不能分享。

**Comment by Heart-beatsss** [comment]
> 我们的标注工具是公司内部开发的一套标注系统，暂未开源，所以暂时还不能分享。

好的，非常感谢，已拿美团offer，这就来内部使用

**Comment by blueseasky** [comment]
> 



> > 我们的标注工具是公司内部开发的一套标注系统，暂未开源，所以暂时还不能分享。
> 
> 好的，非常感谢，已拿美团offer，这就来内部使用

**Comment by blueseasky** [comment]
> > 
> 
> > > 我们的标注工具是公司内部开发的一套标注系统，暂未开源，所以暂时还不能分享。
> > 
> > 
> > 好的，非常感谢，已拿美团offer，这就来内部使用

恭喜恭喜，欢迎加入美团。

**Comment by Heart-beatsss** [comment]
> 

哈哈哈好的，感谢！
