### ISSUE TITLE
文章中BERT模型的疑问

### ISSUE THREAD

**Issue by Dinxin** [Meituan-Dianping/asap#4]
本文的BERT模型应该是采用单阶段的方法来解决方面级的情感分类吧，一共有18个方面，每个方面有3类。
但是，不应该再多出一个类来表示评论中是否包含该方面的信息吗？针对每个方面进行情感分类的时候，用的是交叉熵损失函数吧。这样的话，不就默认评论包含所有的方面信息吗？

**Comment by blueseasky** [comment]
非常感谢关注我们的工作，我们论文的方案是采用多任务的方式来解决ABSA问题。典型的ABSA任务是给定文本包含的Aspect，进而判断在该Aspect上的情感倾向。确实不可能每段评论文本都包含所有Aspect信息，在具体实现中我们定义了一个mask vector [p1, p2, ..., pN ] 来提示哪些aspect被包含，包含pi=1，不包含pi=0，计算loss的时候只会计算被包含aspect上的损失。详情请关注我们论文第四章节Methodology部分，我们发布的数据是有aspect未被包含这一类别信息的。

**Comment by Dinxin** [comment]
模型在验证集和测试集上做评估的时候，也是假定事先就知道了评论文本中包含了哪些aspect吧？

**Comment by fengzi1013** [comment]
你好，想问下你后面怎么解决的这个问题呢？

**Comment by monk678** [comment]
> 模型在验证集和测试集上做评估的时候，也是假定事先就知道了评论文本中包含了哪些aspect吧？

想请问这个问题是怎么解决的呢？预测的时候，是假定已经知道文本中挺提及了哪些aspect么？

**Comment by bujiahao** [comment]
> 模型在验证集和测试集上做评估的时候，也是假定事先就知道了评论文本中包含了哪些aspect吧？

是的，acsa本身的任务定义就是需要知道文本包含哪些aspect

**Comment by bujiahao** [comment]
> > 模型在验证集和测试集上做评估的时候，也是假定事先就知道了评论文本中包含了哪些aspect吧？
> 
> 想请问这个问题是怎么解决的呢？预测的时候，是假定已经知道文本中挺提及了哪些aspect么？

是的

**Comment by bujiahao** [comment]
> > 模型在验证集和测试集上做评估的时候，也是假定事先就知道了评论文本中包含了哪些aspect吧？
> 
> 想请问这个问题是怎么解决的呢？预测的时候，是假定已经知道文本中挺提及了哪些aspect么？

是的。ACSA任务定义就是给定aspect，判断情感极性

**Comment by monk678** [comment]
> > > 模型在验证集和测试集上做评估的时候，也是假定事先就知道了评论文本中包含了哪些aspect吧？
> > 
> > 
> > 想请问这个问题是怎么解决的呢？预测的时候，是假定已经知道文本中挺提及了哪些aspect么？
> 
> 是的。ACSA任务定义就是给定aspect，判断情感极性

感谢解答
