### ISSUE TITLE
A question about the number of labels

### ISSUE THREAD

**Issue by YIzhongyue** [Meituan-Dianping/asap#5]
Thanks for your extremely great work.

I have a question about the number of labels _C_ mentioned in **4.2 section**.

In your dataset, it seems that there are 4 labels for one aspect-category (1 - _positive_, 0 - _neural_, -1 - _negative_, -2 - _not mentioned_), but in the ACSA part, it looks like _C_ is equal to 3 (_positive_, _neural_, _negative_)

> _C_ is the number of labels (i.e, 3 in our task).

so, I wonder why the label _not mentioned_ was scrapped. 

I have noticed that the gate function p_i is used to ensure only the mentioned aspect categories can participate in the calculation of the loss function. 
but it seems like the gate function p_i is not a trainable parameter, so when using the trained model to do prediction, how the model knows which aspect-category are mentioned in a review?

for example, for an input review _R_ written by a user, 
the output of the ACSA part might be: 

```
\hat{y}_1 = [0.7, 0.2, 0.1] 
\hat{y}_2 = [0.5, 0.2, 0.3]
...
\hat{y}_18 = [0.05, 0.05, 0.9]
```

(Please correct me if I have misunderstood something)

in this case, we can know that this user has positive sentiment with the first and second aspect-category, and has negative sentiment with the 18th aspect-category, but how do we know which aspect-category are mentioned in this review?

**Comment by bujiahao** [comment]
> Thanks for your extremely great work.
> 
> I have a question about the number of labels _C_ mentioned in **4.2 section**.
> 
> In your dataset, it seems that there are 4 labels for one aspect-category (1 - _positive_, 0 - _neural_, -1 - _negative_, -2 - _not mentioned_), but in the ACSA part, it looks like _C_ is equal to 3 (_positive_, _neural_, _negative_)
> 
> > _C_ is the number of labels (i.e, 3 in our task).
> 
> so, I wonder why the label _not mentioned_ was scrapped.
> 
> I have noticed that the gate function p_i is used to ensure only the mentioned aspect categories can participate in the calculation of the loss function. but it seems like the gate function p_i is not a trainable parameter, so when using the trained model to do prediction, how the model knows which aspect-category are mentioned in a review?
> 
> for example, for an input review _R_ written by a user, the output of the ACSA part might be:
> 
> ```
> \hat{y}_1 = [0.7, 0.2, 0.1] 
> \hat{y}_2 = [0.5, 0.2, 0.3]
> ...
> \hat{y}_18 = [0.05, 0.05, 0.9]
> ```
> 
> (Please correct me if I have misunderstood something)
> 
> in this case, we can know that this user has positive sentiment with the first and second aspect-category, and has negative sentiment with the 18th aspect-category, but how do we know which aspect-category are mentioned in this review?

hi，the label "-2 - not mentioned" is not used to train model , it serves as a placeholder for format beauty. 
The ACSA task aims to predict sentiment polarities on given aspect categories. The gate function p_i needs to be given by  expert instead of being learned from the model, both in training and prediction stages.

I hope this helps!
