### ISSUE TITLE
Can you make your experimental model publicly available for reproduction?

### ISSUE THREAD

**Issue by yunbujian** [Meituan-Dianping/asap#6]
Your work is extremely valuable!

If possible, could you make your experimental model publicly available for replication?

Thanks in advance!

**Comment by bujiahao** [comment]
> Your work is extremely valuable!
> 
> If possible, could you make your experimental model publicly available for replication?
> 
> Thanks in advance!

hi，sorry that we wiil not release the full code because of copyright issues. 
Thank you for your attention to our work
